[package]
name = "fvp-unpacker-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
fvp-unpacker-core = { path = "../fvp-unpacker-core" }
memmap2 = "0.9.9"
rayon = "1.11.0"
clap = { version = "4.5.54", features = ["derive"] }
comfy-table = "7.2.1"
